echo Testing front end....
echo Testing front end 2....
echo Testing back end....
echo Testing back end 2....
echo Testing concurrency....
echo Testing web access....
echo Testing interface integration....
echo Test complete! 100/100
echo 100
